server:
  port: 8080
  servlet:
    contextPath: /mssivimss-envio-correos
correos:
  user: 'eduardo.flores@people-media.com.mx'
  password: 'eduardo0512'
  bandera: 'true'
  protocolo: 'TLSv1.2'
  host: 'smtp.gmail.com'
  port: '587'

jwt:
  secretkey-dominios: funcionamuybiendominio